### ISSUE TITLE
How do i add using Gradle ?

### ISSUE THREAD

**Issue by mmanishh** [matrixxun/ProductTour#5]
Is there any gradle library to add in my project ? How do i add into my project ? Is there any jar files?

**Comment by goodlifechris** [comment]
yeah ... ensure that you are using the android studio since it already uses gradle as its default build system. To add a library in gradle select your app under project and create a new>> MODULE on left clicking and add your library either as JAR orAndroid library (Check the file extension of the library.

Let me know if its not clear
.....
For projects that has a remote library add as dependencies in gradle as such to add support.compact
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'  
    }

**Comment by mmanishh** [comment]
I was asking is there any gradle repo ? What is the package name to add in gradle as like "'com.android.support:design:23.1.1'" for design support library

**Comment by goodlifechris** [comment]
are u adding gradle or a library?

**Comment by mmanishh** [comment]
I want to use gradle

**Comment by goodlifechris** [comment]
whats your environment? Android studio or eclipse or?

**Comment by mmanishh** [comment]
I want to use gradle so obviously i am using Android Studio ?

**Comment by goodlifechris** [comment]
Thats okay then ... gradle is the default build system meaning you are already using gradle for ur project ...maybe lets say u want to add a library through gradle ryt?

**Comment by mmanishh** [comment]
Plz i just want to know the gradle repo like 'com.android.support:appcompat-v7:23.1.1'  for this lib . CAn u provide me or not ?

**Comment by goodlifechris** [comment]
```
compile 'com.android.support:appcompat-v7:23.1.
```

am not getting u clearly  and thats y am asking a few question. feel free when u are ready to be clear

**Comment by mmanishh** [comment]
I mean what is the gradle repo for this project as we use 

>    compile 'com.facebook.android:facebook-android-sdk:4.1.0'
> for facebook sdk.

**Comment by goodlifechris** [comment]
I remember importing this project instead of opening so that gradle can take place...Please try importing the project

**Comment by goodlifechris** [comment]
else change the word repo and use a better explanation

**Comment by oliverhausler** [comment]
You can use jitpack.io to pull any Github project which isn't hosted on Maven.

**Comment by mmanishh** [comment]
Thanks oliver hausler

**Comment by black-snow** [comment]
This really needs a release on mavencentral or jcenter.
